# Demo 5: **Tập tin dữ liệu**
<u>Nội dung</u>: Thư viện PANDAS
*   Series
*   DataFrame
*   Kết nối với Microsoft SQL Server

<u>Cập nhật</u>: **07/2024**

---
### **MÔI TRƯỜNG TRIỂN KHAI ỨNG DỤNG**
---

In [3]:
## Kết nối Google Drive
from google.colab import drive
drive.mount('/content/gdrive', force_remount = True)
folder = '/content/gdrive/My Drive/Colab Notebooks/DA/Classnote'

Mounted at /content/gdrive

In [4]:
## Các thư viện
import numpy  as np
import pandas as pd

---
### **1. Series**
---


*   Mảng một chiều
*   Có thể tự định nghĩa index của phần tử
*   Các phần tử có thể trùng index

##### *Tạo series chứa các phần tử*

In [ ]:
## Sử dụng chỉ số (ngầm định: 0, 1, 2, ...)
s = pd.Series([9, 2, 7, 1, 6])  #Xem như một mảng một chiều, dưới góc nhìn của pandas -> series
print('Số phần tử :', s.size)

print(s, '\n')

print('Các CHỈ SỐ :', s.index) #Có thể tự định nghĩa các chỉ số cho các phần tử, hoặc xài ngầm định
print('Các CHỈ SỐ :', s.axes)
print('Các GIÁ TRỊ:', s.values) # kiểu array, không có dấu , phân cách

Số phần tử : 5
0    9
1    2
2    7
3    1
4    6
dtype: int64

Các CHỈ SỐ : RangeIndex(start=0, stop=5, step=1)
Các CHỈ SỐ : [RangeIndex(start=0, stop=5, step=1)]
Các GIÁ TRỊ: [9 2 7 1 6]

In [ ]:
## Sử dụng labels với series (labels KHÁC NHAU)
##  Tạo series từ list
s = pd.Series([9, 2, 7, 1, 6], index = ['P1', 'P2', 'P3', 'P4', 'P5'])
print('Các GIÁ TRỊ của s:', s.values)
print('Các CHỈ SỐ  của s:', s.index)

## Sử dụng labels với series (labels có thể TRÙNG NHAU !)
s = pd.Series([9, 2, 7, 1, 6], index = ['P1', 'P2', 'P3', 'P2', 'P5'])
print('Các GIÁ TRỊ của s:', s.values)
print('Các CHỈ SỐ  của s:', s.index)

Các GIÁ TRỊ của s: [9 2 7 1 6]
Các CHỈ SỐ  của s: Index(['P1', 'P2', 'P3', 'P4', 'P5'], dtype='object')
Các GIÁ TRỊ của s: [9 2 7 1 6]
Các CHỈ SỐ  của s: Index(['P1', 'P2', 'P3', 'P2', 'P5'], dtype='object')

In [ ]:
## Sử dụng dictionary (keys KHÁC NHAU)
## Tạo series từ dictionary
transactions = {'P1':9, 'P2':2, 'P3':7, 'P4':1, 'P5':6}
s            = pd.Series(transactions)
print('Các GIÁ TRỊ của s:', s.values)
print('Các CHỈ SỐ  của s:', s.index)

## Sử dụng dictionary (keys TRÙNG NHAU --> sai sót do loại bỏ phần tử !)
transactions = {'P1':9, 'P2':2, 'P3':7, 'P2':1, 'P5':6}
s            = pd.Series(transactions)
print('Các GIÁ TRỊ của s:', s.values)
print('Các CHỈ SỐ  của s:', s.index)

Các GIÁ TRỊ của s: [9 2 7 1 6]
Các CHỈ SỐ  của s: Index(['P1', 'P2', 'P3', 'P4', 'P5'], dtype='object')
Các GIÁ TRỊ của s: [9 1 7 6]
Các CHỈ SỐ  của s: Index(['P1', 'P2', 'P3', 'P5'], dtype='object')

##### *Thêm phần tử mới vào series (xem như dictionary)*

In [ ]:
## Sử dụng labels với series (labels KHÁC NHAU)
s       = pd.Series([9, 2, 7, 1, 6], index = ['P1', 'P2', 'P3', 'P4', 'P5'])
s['P6'] = 100 # new index = 'P6'
print(s)

P1      9
P2      2
P3      7
P4      1
P5      6
P6    100
dtype: int64

##### Truy cập các phần tử của series: **indexing**, **fancy indexing**, **slicing** (implicit index), **masking**

In [ ]:
## Sử dụng các cơ chế
s = pd.Series([9, 2, 7, 1, 6])
print('Phần tử thứ 3:', s[2])                       # indexing
print('Phần tử thứ 2 và thứ 4:', s[[1, 3]].values)  # fancy indexing
print('Phần tử thứ 2 --> 4:', s[1:4].values)        # slicing
print('Phần tử > 6:', s[s > 6].values)              # masking

Phần tử thứ 3: 7
Phần tử thứ 2 và thứ 4: [2 1]
Phần tử thứ 2 --> 4: [2 7 1]
Phần tử > 6: [9 7]

In [ ]:
## Sử dụng labels (labels KHÁC NHAU)
s = pd.Series([9, 2, 7, 1, 6], index = ['P2', 'P1', 'P3', 'P5', 'P4'])
print('Số lượng mặt hàng P3 =', s['P3'])
print('Số lượng mặt hàng P3, P4:', s[['P3', 'P4']].values) # fancy indexing
print('Số lượng mặt hàng P3-P4:', s['P3':'P4'].values)
print('Số lượng mặt hàng thứ 3 đến thứ 5:', s[2:5].values)

## Sử dụng labels (labels TRÙNG NHAU)
s = pd.Series([9, 2, 7, 1, 6], index = ['P2', 'P3', 'P3', 'P5', 'P4'])
print('\nSố lượng mặt hàng P3 =', s['P3'].values)
print('Số lượng mặt hàng P3, P4:', s[['P3', 'P4']].values)
print('Số lượng mặt hàng P3-P4:', s['P3':'P4'].values)
## 'P3' đầu tiên; nếu thứ tự labels trong dữ liệu 'P3', 'P4', 'P3' --> error

Số lượng mặt hàng P3 = 7
Số lượng mặt hàng P3, P4: [7 6]
Số lượng mặt hàng P3-P4: [7 1 6]
Số lượng mặt hàng thứ 3 đến thứ 5: [7 1 6]

Số lượng mặt hàng P3 = [2 7]
Số lượng mặt hàng P3, P4: [2 7 6]
Số lượng mặt hàng P3-P4: [2 7 1 6]

In [ ]:
## Sử dụng dictionary (keys KHÁC NHAU)
transactions = {'P2':9, 'P1':2, 'P3':7, 'P5':1, 'P4':6}
s = pd.Series(transactions)
print('Số lượng mặt hàng P3 =', s['P3'])
print('Số lượng mặt hàng P3, P4:', s[['P3', 'P4']].values)
print('Số lượng mặt hàng P3-P4:', s['P3':'P4'].values)
print('Số lượng mặt hàng thứ 3 đến thứ 5:', s[2:5].values)

Số lượng mặt hàng P3 = 7
Số lượng mặt hàng P3, P4: [7 6]
Số lượng mặt hàng P3-P4: [7 1 6]
Số lượng mặt hàng thứ 3 đến thứ 5: [7 1 6]

In [5]:
## Sử dụng loc --> EXPLICIT index   ##Có thể dùng cho chỉ số định nghĩa hoặc ngầm định
s = pd.Series([9, 2, 7, 1, 6], index = ['P2', 'P1', 'P3', 'P5', 'P4'])
print('Phần tử từ P1 đến P5 =', s.loc['P1':'P5'].values)

## Sử dụng iloc --> IMPLICIT index  ##Chỉ dùng cho chỉ số ngầm định
print('Phần tử từ 1 đến 3 =', s.iloc[1:4].values)

Phần tử từ P1 đến P5 = [2 7 1]
Phần tử từ 1 đến 3 = [2 7 1]

##### *Xóa phần tử của series*

In [ ]:
## Sử dụng chỉ số ngầm định (chỉ định bằng list, không dùng slice)
s = pd.Series([9, 2, 7, 1, 6])
print('Xóa phần tử 2 và 4:', s.values, '-->', s.drop([1,3]).values)

## Sử dụng labels
s = pd.Series([9, 2, 7, 1, 6], index = ['P2', 'P1', 'P3', 'P5', 'P4'])
print('Xóa phần tử 2 và 4:', s.values, '-->', s.drop(['P1', 'P5']).values)

## Xóa bỏ các phần tử có GIÁ TRỊ trùng lắp
s = pd.Series([9, 2, 7, 9, 6])
print('Xóa phần tử trùng lắp:', s.values, '-->', s.drop_duplicates().values)

Xóa phần tử 2 và 4: [9 2 7 1 6] --> [9 7 6]
Xóa phần tử 2 và 4: [9 2 7 1 6] --> [9 7 6]
Xóa phần tử trùng lắp: [9 2 7 9 6] --> [9 2 7 6]

##### *Sử dụng một số phương thức của series*

In [ ]:
s = pd.Series([9, 2, 7, 1, 6], index = ['P2', 'P1', 'P3', 'P5', 'P4'])
print('MAX            =', s.max())
print('MIN            =', s.min())
print('SUM            =', s.sum())
print('Cumulative SUM =', s.cumsum().values, '\n')
print(s.describe())

MAX            = 9
MIN            = 1
SUM            = 25
Cumulative SUM = [ 9 11 18 19 25]

count    5.000000
mean     5.000000
std      3.391165
min      1.000000
25%      2.000000
50%      6.000000
75%      7.000000
max      9.000000
dtype: float64

---
### **2. DataFrame**
---


*   Có cấu trúc tương tự ma trận 2 chiều ở bên numpy

In [ ]:
##------------------------------------------------------------------------------
## * Series    có thể được xem như 1 "cột" dữ liệu (đi kèm với 1 cột chỉ số)
## * Dataframe có thể được xem như nhiều series được ghép nối theo hàng dọc
##             hay là tập hợp các series CHIA SẺ cùng chỉ số
##             --> tạo ra bảng dữ liệu 2 chiều với các 'columns names'
##------------------------------------------------------------------------------

##### *Tạo dataframe*

In [7]:
## Tạo dataframe từ 1 ma trận (2D-array)
matrix = np.random.rand(5, 3)
df     = pd.DataFrame(matrix)
print(df, '\n')

## Gán tên cột
df = pd.DataFrame(matrix, columns = ['f1', 'f2', 'f3'])
print(df)

## Gán tên cột và dòng
df = pd.DataFrame(matrix, index = ['u1', 'u2', 'u3', 'u4', 'u5'], columns = ['f1', 'f2', 'f3'])
print(df, '\n')

          0         1         2
0  0.375811  0.470369  0.233218
1  0.814111  0.234208  0.665142
2  0.307917  0.288729  0.739732
3  0.303341  0.858823  0.901017
4  0.976818  0.266832  0.340356

         f1        f2        f3
0  0.375811  0.470369  0.233218
1  0.814111  0.234208  0.665142
2  0.307917  0.288729  0.739732
3  0.303341  0.858823  0.901017
4  0.976818  0.266832  0.340356
          f1        f2        f3
u1  0.375811  0.470369  0.233218
u2  0.814111  0.234208  0.665142
u3  0.307917  0.288729  0.739732
u4  0.303341  0.858823  0.901017
u5  0.976818  0.266832  0.340356

In [8]:
## Tạo dataframe từ 1 series
mahh    = ['P1', 'P2', 'P3', 'P4', 'P5']
tenhh   = pd.Series(['Mặt hàng 1', 'Mặt hàng 2', 'Mặt hàng 3', 'Mặt hàng 4', 'Mặt hàng 5'])
soluong = pd.Series([9, 2, 7, 1, 6])

df    = pd.DataFrame(tenhh, columns = ['tenhh'])
print(df, '\n')

## Tạo dataframe từ nhiều series --> cặp dấu bao {}
df   = pd.DataFrame({'mahh' : mahh, 'tenhh' : tenhh, 'soluong' : soluong})
print(df)

        tenhh
0  Mặt hàng 1
1  Mặt hàng 2
2  Mặt hàng 3
3  Mặt hàng 4
4  Mặt hàng 5

  mahh       tenhh  soluong
0   P1  Mặt hàng 1        9
1   P2  Mặt hàng 2        2
2   P3  Mặt hàng 3        7
3   P4  Mặt hàng 4        1
4   P5  Mặt hàng 5        6

In [9]:
## Tạo dataframe từ dictionary --> chuyển sang series bằng pd.Series()
tenhh_dict   = {'P1' : 'Mặt hàng 1', 'P2' : 'Mặt hàng 2', 'P3' : 'Mặt hàng 3',
                'P4' : 'Mặt hàng 4', 'P5' : 'Mặt hàng 5'}
soluong_dict = {'P1' : 9, 'P2' : 2, 'P3' : 7, 'P4' : 1, 'P5' : 6}
df           = pd.DataFrame({'tenhh': pd.Series(tenhh_dict), 'soluong': pd.Series(soluong_dict)})
print(df)

         tenhh  soluong
P1  Mặt hàng 1        9
P2  Mặt hàng 2        2
P3  Mặt hàng 3        7
P4  Mặt hàng 4        1
P5  Mặt hàng 5        6

In [10]:
## Tạo dataframe từ 1 list
lst = [['Mặt hàng 1', 9], ['Mặt hàng 2', 2], ['Mặt hàng 3', 7], ['Mặt hàng 4', 1],
       ['Mặt hàng 5', 6]]
df  = pd.DataFrame(lst, columns = ['tenhh', 'soluong'], index = mahh)
print(df, '\n')

lst = [['PA1', 'Mặt hàng 1', 9], ['PA2', 'Mặt hàng 2', 2], ['PA3', 'Mặt hàng 3', 7],
       ['PA4', 'Mặt hàng 4', 1], ['PA5', 'Mặt hàng 5', 6]]
df  = pd.DataFrame(lst, columns = ['mahh', 'tenhh', 'soluong'])
print(df)

         tenhh  soluong
P1  Mặt hàng 1        9
P2  Mặt hàng 2        2
P3  Mặt hàng 3        7
P4  Mặt hàng 4        1
P5  Mặt hàng 5        6

  mahh       tenhh  soluong
0  PA1  Mặt hàng 1        9
1  PA2  Mặt hàng 2        2
2  PA3  Mặt hàng 3        7
3  PA4  Mặt hàng 4        1
4  PA5  Mặt hàng 5        6

In [12]:
## Tạo dataframe từ tập tin Excel
df1_xls = pd.read_excel(folder + '/Data/Data.xls') # ngầm định mở sheet đầu tiên
print(df1_xls.head().to_string(index = False))

df2_xls = pd.read_excel(folder + '/Data/Data.xls', sheet_name = 'Iris') # chỉ định sheet được mở
print(df2_xls.head().to_string(index = False))

## Tạo dataframe từ tập tin CSV
df3_csv = pd.read_csv(folder + '/Data/Insurance.csv')
print(df3_csv.head().to_string(index = False))

 age    sex    bmi  children smoker    region     charges
  19 female 27.900         0    yes southwest 16884.92400
  18   male 33.770         1     no southeast  1725.55230
  28   male 33.000         3     no southeast  4449.46200
  33   male 22.705         0     no northwest 21984.47061
  32   male 28.880         0     no northwest  3866.85520
 sepallength  sepalwidth  petallength  petalwidth     species
         5.1         3.5          1.4         0.2 Iris-setosa
         4.9         3.0          1.4         0.2 Iris-setosa
         4.7         3.2          1.3         0.2 Iris-setosa
         4.6         3.1          1.5         0.2 Iris-setosa
         5.0         3.6          1.4         0.2 Iris-setosa
 age    sex    bmi  children smoker    region     charges
  19 female 27.900         0    yes southwest 16884.92400
  18   male 33.770         1     no southeast  1725.55230
  28   male 33.000         3     no southeast  4449.46200
  33   male 22.705         0     no northwest 21984.47061
  32   male 28.880         0     no northwest  3866.85520

##### *Xem sơ bộ thông tin của dataframe*

In [13]:
## Cấu trúc dataframe
df = pd.read_excel(folder + '/Data/Data.xls', sheet_name = 'Insurance')

#In ra meta data
  ## Data: dùng để mô tả cho thực tế
  ## Meta data: dùng để mô tả cho dữ liệu
print(df.info(), '\n----------\n')
print('Các CỘT   :', df.columns.tolist())
print('Các CHỈ SỐ:', df.index.tolist())
print('Số dòng m =', df.shape[0])
print('Số cot  n =', df.shape[1], '\n----------')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None
----------

Các CỘT   : ['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']
Các CHỈ SỐ: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337]
Số dòng m = 1338
Số cot  n = 7
----------

In [14]:
## Nội dung các dòng
print(df.head(), '\n----------')  # 5 (default) dòng đầu
print(df.head(2), '\n----------') # 2 dòng đầu

## Nên quan sát tail, bên dưới vì thường dữ liệu bị thiếu sẽ nằm ở dưới, ít khi nằm trên -> Dễ thấy bất thường hơn
print(df.tail())  # 5 (default) dòng cuối
print(df.tail(2), '\n----------') # 2 dòng cuối

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
----------
   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
----------
      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603
      age     sex    bmi  children smoker     region     charges
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603
----------

##### *Thao tác trên CỘT*

In [16]:
## Phép chiếu trên 1 cột
print(df['age'].head(3), '\n---\n') # <column name> như là chỉ số (dictionary-style indexing)
print(df.age.head(3), '\n---\n') # <column name> như là thuộc tính (attribute-style access)
##                                  <column name>: chuỗi, không trùng methods của DataFrame
print(df['age'] is df.age) # kiểm tra có giống nhau

## Phép chiếu trên nhiều hơn 1 cột
df_proj2 = df[['age','sex','smoker']]
print(df_proj2.head(3))
print('Tuổi trung bình:', int(df_proj2['age'].mean())) # trị trung bình của cột

0    19
1    18
2    28
Name: age, dtype: int64
---

0    19
1    18
2    28
Name: age, dtype: int64
---

True
   age     sex smoker
0   19  female    yes
1   18    male     no
2   28    male     no
Tuổi trung bình: 39

In [17]:
## Thêm cột mới
## Thêm một tên chưa có, thì mặc định là thêm cột mới
df['year_of_birth'] = 2022 - df['age'] # tên cột mới
print(df.head(3), '\n----------')

   age     sex    bmi  children smoker     region     charges  year_of_birth
0   19  female  27.90         0    yes  southwest  16884.9240           2003
1   18    male  33.77         1     no  southeast   1725.5523           2004
2   28    male  33.00         3     no  southeast   4449.4620           1994
----------

In [18]:
## Loại bỏ cột
df2 = df
df2.drop(columns = 'year_of_birth', inplace = True) #Xóa cột trên dữ liệu gốc, không tạo bản copy
print(df2.head(), '\n----------')

df3 = df2.drop(columns = ['smoker', 'region'], inplace = False) # tạo bản copy
print(df2.head(3), '\n----------')
print(df3.head(3))

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
----------
   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620
----------
   age     sex    bmi  children     charges
0   19  female  27.90         0  16884.9240
1   18    male  33.77         1   1725.5523
2   28    male  33.00         3   4449.4620

In [19]:
## Thay thế giá trị của cột theo điều kiện
## df.loc[<condition>, <column name>] = <expression>
np.random.seed(1)
matrix = np.random.randint(0, 100, (10, 3))
df     = pd.DataFrame(matrix, columns = ['f1', 'f2', 'f3'])
print(df.to_string(index = False), '\n')

## Gán f3 = (f2 / 2) đối với những dòng có f2 là số chẵn
df.loc[df["f2"] % 2 == 0, "f3"] = df['f2'] // 2
print(df.to_string(index = False))

 f1  f2  f3
 37  12  72
  9  75   5
 79  64  16
  1  76  71
  6  25  50
 20  18  84
 11  28  29
 14  50  68
 87  87  94
 96  86  13

 f1  f2  f3
 37  12   6
  9  75   5
 79  64  32
  1  76  38
  6  25  50
 20  18   9
 11  28  14
 14  50  25
 87  87  94
 96  86  43

##### *Thao tác trên DÒNG*

In [ ]:
## Truy xuất tất cả các cột với dataframe[<row_idx]
df = pd.read_excel(folder + '/Data/Data.xls', sheet_name = 'Insurance')

print(df[1:2], '\n----------') # dòng 2
print(df[1:3], '\n----------') # dòng 2, 3

## Truy xuất chỉ một số cột dataframe[<row_idx>][<col_idx>]
print(df[1:2]['age'], '\n----------')
print(df[1:3][['age', 'bmi', 'smoker']])

   age   sex    bmi  children smoker     region    charges
1   18  male  33.77         1     no  southeast  1725.5523
----------
   age   sex    bmi  children smoker     region    charges
1   18  male  33.77         1     no  southeast  1725.5523
2   28  male  33.00         3     no  southeast  4449.4620
----------
1    18
Name: age, dtype: int64
----------
   age    bmi smoker
1   18  33.77     no
2   28  33.00     no

In [ ]:
## Truy xuất dữ liệu theo dòng với dataframe.loc[<row_idx>, <col_idx>]
print('Các dòng từ chỉ số [1] đến chỉ số [3]')
print(df.loc[1:3], '\n----------')

print('Tuổi của dòng có chỉ số [1] là ', df.loc[1]['age'], '\n----------')
print(df.loc[1:3][['age', 'smoker']]) # lưu ý: PHẢI CÓ   [] đối với chỉ số cột
print(df.loc[1:3, 'age':'smoker'])    # lưu ý: KHÔNG CẦN [] đối với chỉ số cột

Các dòng từ chỉ số [1] đến chỉ số [3]
   age   sex     bmi  children smoker     region      charges
1   18  male  33.770         1     no  southeast   1725.55230
2   28  male  33.000         3     no  southeast   4449.46200
3   33  male  22.705         0     no  northwest  21984.47061
----------
Tuổi của dòng có chỉ số [1] là  18
----------
   age smoker
1   18     no
2   28     no
3   33     no
   age   sex     bmi  children smoker
1   18  male  33.770         1     no
2   28  male  33.000         3     no
3   33  male  22.705         0     no

In [ ]:
## Truy xuất dữ liệu theo dòng với dataframe.iloc[<row_idx>, <col_idx>]
print('Các dòng từ chỉ số [1] đến chỉ số [3-1]')
print(df.iloc[1:3], '\n----------') # dòng 2, 3

print(df.iloc[1]['age'], '\n----------')
print(df.iloc[1:3][['age', 'smoker']]) # lưu ý: PHẢI CÓ [] đối với chỉ số cột
print(df.iloc[1:3], [[0, 5]])          # lưu ý: PHẢI CÓ [] đối với chỉ số cột
print(df.iloc[1:3, 0:5])               # lưu ý: không dùng slicing với LABELS

Các dòng từ chỉ số [1] đến chỉ số [3-1]
   age   sex    bmi  children smoker     region    charges
1   18  male  33.77         1     no  southeast  1725.5523
2   28  male  33.00         3     no  southeast  4449.4620
----------
18
----------
   age smoker
1   18     no
2   28     no
   age   sex    bmi  children smoker     region    charges
1   18  male  33.77         1     no  southeast  1725.5523
2   28  male  33.00         3     no  southeast  4449.4620 [[0, 5]]
   age   sex    bmi  children smoker
1   18  male  33.77         1     no
2   28  male  33.00         3     no

In [ ]:
## Duyệt các dòng của dataframe
df = pd.read_excel(folder + '/Data/Data.xls', sheet_name = 'Insurance')

df = df.head()
for idx, row in df.iterrows():
    print(f'* Dòng {idx}:')
    print(row, '\n')

* Dòng 0:
age                19
sex            female
bmi              27.9
children            0
smoker            yes
region      southwest
charges     16884.924
Name: 0, dtype: object

* Dòng 1:
age                18
sex              male
bmi             33.77
children            1
smoker             no
region      southeast
charges     1725.5523
Name: 1, dtype: object

* Dòng 2:
age                28
sex              male
bmi              33.0
children            3
smoker             no
region      southeast
charges      4449.462
Name: 2, dtype: object

* Dòng 3:
age                  33
sex                male
bmi              22.705
children              0
smoker               no
region        northwest
charges     21984.47061
Name: 3, dtype: object

* Dòng 4:
age                32
sex              male
bmi             28.88
children            0
smoker             no
region      northwest
charges     3866.8552
Name: 4, dtype: object

In [ ]:
## Xử lý như ma trận với dataframe.loc[<row_idx>, <col_idx>]
##                    và dataframe.iloc[<row_idx>, <col_idx>]
matrix = np.random.rand(5, 6)
df     = pd.DataFrame(matrix, columns = ['f1', 'f2', 'f3', 'f4', 'f5', 'f6'])
print(df, '\n')

print('Dòng 2:', df.values[1], '\n')
print('[dòng2-dòng4][cột3:cột5]:\n', df.loc[1:3, 'f3':'f5'], '\n') # hữu dụng khi index không sắp thứ tự
print('[dòng2-dòng4][cột3:cột5]:\n', df.iloc[1:4, 2:5], '\n')
print(df.loc[df.f1 > 0.3, ['f1', 'f2', 'f6']])

         f1        f2        f3        f4        f5        f6
0  0.715971  0.802758  0.092801  0.518153  0.865020  0.829147
1  0.829603  0.273050  0.059243  0.670528  0.593066  0.671654
2  0.411788  0.197551  0.289630  0.142120  0.783314  0.412539
3  0.034171  0.624030  0.660636  0.298495  0.446135  0.222125
4  0.073364  0.469239  0.096172  0.903370  0.119490  0.524799

Dòng 2: [0.82960336 0.27304997 0.0592432  0.67052804 0.59306552 0.6716541 ]

[dòng2-dòng4][cột3:cột5]:
          f3        f4        f5
1  0.059243  0.670528  0.593066
2  0.289630  0.142120  0.783314
3  0.660636  0.298495  0.446135

[dòng2-dòng4][cột3:cột5]:
          f3        f4        f5
1  0.059243  0.670528  0.593066
2  0.289630  0.142120  0.783314
3  0.660636  0.298495  0.446135

         f1        f2        f6
0  0.715971  0.802758  0.829147
1  0.829603  0.273050  0.671654
2  0.411788  0.197551  0.412539

In [ ]:
## Phép chọn những dòng thỏa điều kiện (masking)
df     = pd.read_excel(folder + '/Data/Data.xls', sheet_name = 'Insurance')
df_ext = df[(df.age > 60) & (df.smoker == 'no')]
print(df_ext.head())
print(df_ext.index) # index của những dòng thỏa điều kiện

    age     sex     bmi  children smoker     region      charges
26   63  female  23.085         0     no  northeast  14451.83515
33   63    male  28.310         0     no  northwest  13770.09790
36   62  female  32.965         3     no  northwest  15612.19335
62   64    male  24.700         1     no  northwest  30166.61817
66   61  female  39.100         2     no  southwest  14235.07200
Int64Index([  26,   33,   36,   62,   66,  131,  170,  190,  199,  208,  287,
             332,  335,  337,  341,  343,  370,  378,  379,  398,  402,  418,
             462,  480,  491,  493,  499,  531,  534,  542,  550,  552,  573,
             588,  603,  635,  642,  722,  752,  768,  770,  789,  801,  825,
             830,  851,  868,  894,  895,  908,  918,  920,  921,  928,  944,
             962,  997, 1012, 1034, 1051, 1068, 1071, 1079, 1084, 1125, 1187,
            1236, 1322, 1325],
           dtype='int64')

In [ ]:
## Sắp xếp dữ liệu: ngầm định TĂNG DẦN
print(df.sort_values(by = ['sex', 'age']), '\n----------')

## Chỉ định thứ tự sắp xếp TĂNG, GIẢM cho từng cột
print(df.sort_values(by = ['sex', 'age'], ascending = [True, False]))

      age     sex     bmi  children smoker     region      charges
31     18  female  26.315         0     no  northeast   2198.18985
46     18  female  38.665         2     no  northeast   3393.35635
50     18  female  35.625         0     no  northeast   2211.13075
102    18  female  30.115         0     no  northeast  21344.84670
161    18  female  36.850         0    yes  southeast  36149.48350
...   ...     ...     ...       ...    ...        ...          ...
635    64    male  38.190         0     no  northeast  14410.93210
752    64    male  37.905         0     no  northwest  14210.53595
1051   64    male  26.410         0     no  northeast  14394.55790
1241   64    male  36.960         2    yes  southeast  49577.66240
1265   64    male  23.760         0    yes  southeast  26926.51440

[1338 rows x 7 columns]
----------
      age     sex     bmi  children smoker     region      charges
94     64  female  31.300         2    yes  southwest  47291.05500
199    64  female  39.330         0     no  northeast  14901.51670
328    64  female  33.800         1    yes  southwest  47928.03000
378    64  female  30.115         3     no  northwest  16455.70785
402    64  female  32.965         0     no  northwest  14692.66935
...   ...     ...     ...       ...    ...        ...          ...
1244   18    male  33.330         0     no  southeast   1135.94070
1283   18    male  30.030         1     no  southeast   1720.35370
1296   18    male  26.125         0     no  northeast   1708.92575
1315   18    male  28.310         1     no  northeast  11272.33139
1317   18    male  53.130         0     no  southeast   1163.46270

[1338 rows x 7 columns]

In [ ]:
## Thêm dòng mới vào phía cuối của dataframe
df = pd.read_excel(folder + '/Data/Data.xls', sheet_name = 'Insurance')
print('Số dòng BAN ĐẦU =', df.shape[0])

new_rows = df.head(3)
df = pd.concat([df, new_rows])
print('Số dòng sau khi THÊM VÀO CUỐI =', df.shape)

Số dòng BAN ĐẦU = 1338
Số dòng sau khi THÊM VÀO CUỐI = (2676, 7)

<ipython-input-44-3bb120fc597d>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df)

In [ ]:
## Xóa dòng của dataframe
## shape[0]: số dòng
## shape[1]: số cột
## shape: hiện cả hai
df = pd.read_excel(folder + '/Data/Data.xls', sheet_name = 'Insurance')
print('Số dòng TRƯỚC khi xóa:', df.shape[0])
idx_drop = (df.sex == 'male') & (df.smoker == 'no') # idx những dòng sẽ bị xóa
df.drop(df[idx_drop].index, inplace = True)
print('Số dòng SAU   khi xóa:', df.shape[0])

Số dòng TRƯỚC khi xóa: 1338
Số dòng SAU   khi xóa: 821

In [ ]:
## Lưu dữ liệu của dataframe lên tập tin
df.to_csv(folder + '/Data/Ketqua.csv')
df.to_excel(folder + '/Data/Ketqua.xlsx')

---
## **3. Kết nối với Microsoft SQL Server**
---

In [20]:
pip install pymssql

Collecting pymssql
  Downloading pymssql-2.3.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (7.1 kB)
Downloading pymssql-2.3.1-cp310-cp310-manylinux_2_28_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 50.3 MB/s eta 0:00:00
Installing collected packages: pymssql
Successfully installed pymssql-2.3.1

In [ ]:
## Từ môi trường cloud không thể kết nối với MS SQL Server trên máy local
##    --> Chạy trên máy local: Jupyter Notebook, ...
from pymssql import connect
conn = connect(server = 'localhost\SQLSERVER2014ENT', database = 'QLGV')

In [ ]:
## Truy cập CSDL
cur = conn.cursor()
sql = "SELECT TOP 10 * FROM SINH_VIEN"
cur.execute(sql)
for row in cur:
    print(row)

conn.close()

('91002', 'Nguyễn Ngọc', 'An', True, datetime.date(1995, 3, 7), '02', 'ÐT', 'CNTT', '2013-2014', 80000.0)
('91007', 'Nguyễn Đồng', 'Nai', True, datetime.date(1995, 5, 12), '41', 'ÐT', 'CNTT', '2013-2014', 0.0)
('91023', 'Nguyễn Hùng', 'Sư', False, datetime.date(1994, 12, 10), '56', 'ÐT', 'CNTT', '2013-2014', 120000.0)
('91024', 'Võ Văn', 'Năm', False, datetime.date(1995, 7, 11), '02', 'ÐT', 'CNTT', '2013-2014', 0.0)
('91045', 'Phạm Sĩ', 'Tử', False, datetime.date(1994, 7, 16), '34', 'ÐT', 'VLLT', '2013-2014', 0.0)
('91088', 'Lưu Thu', 'Vàng', True, datetime.date(1995, 7, 5), '02', 'ÐT', 'VLLT', '2013-2014', 120000.0)
('91102', 'Lê Thị', 'Chín', True, datetime.date(1994, 8, 23), '46', 'ÐT', 'VLLT', '2013-2014', 0.0)
('91109', 'Nguyễn Văn', 'Bốn', False, datetime.date(1992, 11, 24), '02', 'ÐT', 'CNSH', '2013-2014', 80000.0)
('91120', 'Tôn Thất', 'Quyền', False, datetime.date(1991, 12, 18), '02', 'ÐT', 'CNSH', '2013-2014', 0.0)
('91133', 'Hà Thị Giang', 'Long', True, datetime.date(1995, 12, 25), '02', 'ÐT', 'CNSH', '2013-2014', 0.0)